silk/urls.py
from django.urls import path

from silk.views.clear_db import ClearDBView
from silk.views.cprofile import CProfileView
from silk.views.profile_detail import ProfilingDetailView
from silk.views.profile_dot import ProfileDotView
from silk.views.profile_download import ProfileDownloadView
from silk.views.profiling import ProfilingView
from silk.views.raw import Raw
from silk.views.request_detail import RequestView
from silk.views.requests import RequestsView
from silk.views.sql import SQLView
from silk.views.sql_detail import SQLDetailView
from silk.views.summary import SummaryView

app_name = 'silk'
urlpatterns = [
    path(route='', view=SummaryView.as_view(), name='summary'),
    path(route='requests/', view=RequestsView.as_view(), name='requests'),
    path(
        route='request/<int:request_id>/',
        view=RequestView.as_view(),
        name='request_detail',
    ),
    path(
        route='request/<int:request_id>/sql/',
        view=SQLView.as_view(),
        name='request_sql',
    ),
    path(
        route='request/<int:request_id>/sql/<int:sql_id>/',
        view=SQLDetailView.as_view(),
        name='request_sql_detail',
    ),
    path(
        route='request/<int:request_id>/raw/',
        view=Raw.as_view(),
        name='raw',
    ),
    path(
        route='request/<int:request_id>/pyprofile/',
        view=ProfileDownloadView.as_view(),
        name='request_profile_download',
    ),
    path(
        route='request/<int:request_id>/json/',
        view=ProfileDotView.as_view(),
        name='request_profile_dot',
    ),
    path(
        route='request/<int:request_id>/profiling/',
        view=ProfilingView.as_view(),
        name='request_profiling',
    ),
    path(
        route='request/<int:request_id>/profile/<int:profile_id>/',
        view=ProfilingDetailView.as_view(),
        name='request_profile_detail',
    ),
    path(
        route='request/<int:request_id>/profile/<int:profile_id>/sql/',
        view=SQLView.as_view(),
        name='request_and_profile_sql',
    ),
    path(
        route='request/<int:request_id>/profile/<int:profile_id>/sql/<int:sql_id>/',
        view=SQLDetailView.as_view(),
        name='request_and_profile_sql_detail',
    ),
    path(
        route='profile/<int:profile_id>/',
        view=ProfilingDetailView.as_view(),
        name='profile_detail',
    ),
    path(
        route='profile/<int:profile_id>/sql/',
        view=SQLView.as_view(),
        name='profile_sql',
    ),
    path(
        route='profile/<int:profile_id>/sql/<int:sql_id>/',
        view=SQLDetailView.as_view(),
        name='profile_sql_detail',
    ),
    path(route='profiling/', view=ProfilingView.as_view(), name='profiling'),
    path(route='cleardb/', view=ClearDBView.as_view(), name='cleardb'),
    path(
        route='request/<int:request_id>/cprofile/',
        view=CProfileView.as_view(),
        name='cprofile',
    ),
]

silk/views/clear_db.py
import os
import shutil

from django.db import transaction
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import View

from silk.auth import login_possibly_required, permissions_possibly_required
from silk.config import SilkyConfig
from silk.models import Profile, Request, Response, SQLQuery
from silk.utils.data_deletion import delete_model


@method_decorator(transaction.non_atomic_requests, name="dispatch")
class ClearDBView(View):

    @method_decorator(login_possibly_required)
    @method_decorator(permissions_possibly_required)
    def get(self, request, *_, **kwargs):
        return render(request, 'silk/clear_db.html')

    @method_decorator(login_possibly_required)
    @method_decorator(permissions_possibly_required)
    def post(self, request, *_, **kwargs):
        context = {}
        if 'clear_all' in request.POST:
            delete_model(Profile)
            delete_model(SQLQuery)
            delete_model(Response)
            delete_model(Request)
            tables = ['Response', 'SQLQuery', 'Profile', 'Request']
            context['msg'] = 'Cleared data for following silk tables: {}'.format(', '.join(tables))

            if SilkyConfig().SILKY_DELETE_PROFILES:
                dir = SilkyConfig().SILKY_PYTHON_PROFILER_RESULT_PATH
                for files in os.listdir(dir):
                    path = os.path.join(dir, files)
                    try:
                        shutil.rmtree(path)
                    except OSError:
                        os.remove(path)
                context['msg'] += '\nDeleted all profiles from the directory.'

        return render(request, 'silk/clear_db.html', context=context)

silk/views/cprofile.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import View

from silk.auth import login_possibly_required, permissions_possibly_required
from silk.models import Request


class CProfileView(View):

    @method_decorator(login_possibly_required)
    @method_decorator(permissions_possibly_required)
    def get(self, request, *_, **kwargs):
        request_id = kwargs["request_id"]
        silk_request = Request.objects.get(pk=request_id)
        context = {"silk_request": silk_request, "request": request}

        return render(request, "silk/cprofile.html", context)

silk/views/distribution.py
import csv
import contextlib
from six import StringIO
from django.http import HttpResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from silk.models import Request
from silk.auth import login_possibly_required, permissions_possibly_required
from silk.request_filters import get_path_and_filters
from silk.views.requests import RequestsView


class DistributionView(RequestsView):

    @method_decorator(login_possibly_required)
    @method_decorator(permissions_possibly_required)
    def get(self, request, *args, **kwargs):
        group_by = kwargs.get('group_by', None) or 'start_time'
        context = self._create_context(request)
        context.update(group_by=group_by)
        return render(request, 'silk/distribution.html', context)


class DistributionDataView(RequestsView):

    def to_csv(self, queryset):
        with contextlib.closing(StringIO()) as stream:
            writer = csv.writer(stream, delimiter=',')
            writer.writerow(('group', 'value'))
            writer.writerows(queryset)
            return stream.getvalue().encode('utf-8')

    @method_decorator(login_possibly_required)
    @method_decorator(permissions_possibly_required)
    def get(self, request):

        path, _, filters = get_path_and_filters(request, self.session_key_request_filters)
        group_by = request.GET.get('group-by', None) or 'date'

        # properties can't be used in values_list
        get_group = lambda x: x
        if group_by in ('date', 'start', 'hour', 'minute'):
            get_group = getattr(Request, 'get_' + group_by)
            group_by = 'start_time'

        queryset = (
               self._get_objects(show=float('inf'), filters=filters, path=path)
               .values_list(group_by, 'time_taken')
        )
        csv = self.to_csv((get_group(group), value) for group, value in queryset)

        return HttpResponse(csv, content_type='text/csv')

silk/views/profile_detail.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import View

from silk.auth import login_possibly_required, permissions_possibly_required
from silk.models import Profile
from silk.views.code import _code_context, _code_context_from_request


class ProfilingDetailView(View):

    @method_decorator(login_possibly_required)
    @method_decorator(permissions_possibly_required)
    def get(self, request, *_, **kwargs):
        profile_id = kwargs["profile_id"]
        context = {"request": request}
        profile = Profile.objects.get(pk=profile_id)
        file_path = profile.file_path
        line_num = profile.line_num

        context["pos"] = pos = int(request.GET.get("pos", 0))
        if pos:
            context.update(_code_context_from_request(request, prefix="pyprofile_"))

        context["profile"] = profile
        context["line_num"] = file_path
        context["file_path"] = line_num
        context["file_column"] = 5

        if profile.request:
            context["silk_request"] = profile.request
        if file_path and line_num:
            try:
                context.update(_code_context(file_path, line_num, profile.end_line_num))
            except OSError as e:
                if e.errno == 2:
                    context["code_error"] = e.filename + " does not exist."
                else:
                    raise e

        return render(request, "silk/profile_detail.html", context)

silk/views/profiling.py
from django.db.models import Count, Sum
from django.shortcuts import render
from django.template.context_processors import csrf
from django.utils.decorators import method_decorator
from django.views.generic import View

from silk.auth import login_possibly_required, permissions_possibly_required
from silk.models import Profile, Request
from silk.request_filters import BaseFilter, FiltersManager, filters_from_request


class ProfilingView(View):
    show = [5, 10, 25, 100, 250]
    default_show = 25
    order_by = ['Recent',
                'Name',
                'Function Name',
                'Num. Queries',
                'Time',
                'Time on queries']
    defualt_order_by = 'Recent'
    session_key_profile_filters = 'session_key_profile_filters'
    filters_manager = FiltersManager(session_key_profile_filters)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def _get_distinct_values(self, field, silk_request):
        if silk_request:
            query_set = Profile.objects.filter(request=silk_request)
        else:
            query_set = Profile.objects.all()
        function_names = [x[field] for x in query_set.values(field).distinct()]
        # Ensure top, default option is ''
        try:
            function_names.remove('')
        except ValueError:
            pass
        return [''] + function_names

    def _get_function_names(self, silk_request=None):
        return self._get_distinct_values('func_name', silk_request)

    def _get_names(self, silk_request=None):
        return self._get_distinct_values('name', silk_request)

    def _get_objects(self, show=None, order_by=None, name=None, func_name=None, silk_request=None, filters=None):
        if not filters:
            filters = []
        if not show:
            show = self.default_show
        manager = Profile.objects
        if silk_request:
            query_set = manager.filter(request=silk_request)
        else:
            query_set = manager.all()
        if not order_by:
            order_by = self.defualt_order_by
        if order_by == 'Recent':
            query_set = query_set.order_by('-start_time')
        elif order_by == 'Name':
            query_set = query_set.order_by('-name')
        elif order_by == 'Function Name':
            query_set = query_set.order_by('-func_name')
        elif order_by == 'Num. Queries':
            query_set = query_set.annotate(num_queries=Count('queries')).order_by('-num_queries')
        elif order_by == 'Time':
            query_set = query_set.order_by('-time_taken')
        elif order_by == 'Time on queries':
            query_set = query_set.annotate(db_time=Sum('queries__time_taken')).order_by('-db_time')
        elif order_by:
            raise RuntimeError('Unknown order_by: "%s"' % order_by)
        if func_name:
            query_set = query_set.filter(func_name=func_name)
        if name:
            query_set = query_set.filter(name=name)
        for f in filters:
            query_set = f.contribute_to_query_set(query_set)
            query_set = query_set.filter(f)
        return list(query_set[:show])

    def _create_context(self, request, *args, **kwargs):
        request_id = kwargs.get('request_id')
        if request_id:
            silk_request = Request.objects.get(pk=request_id)
        else:
            silk_request = None
        show = request.GET.get('show', self.default_show)
        order_by = request.GET.get('order_by', self.defualt_order_by)
        if show:
            show = int(show)
        func_name = request.GET.get('func_name', None)
        name = request.GET.get('name', None)
        filters = self.filters_manager.get(request)
        context = {
            'show': show,
            'order_by': order_by,
            'request': request,
            'func_name': func_name,
            'options_show': self.show,
            'options_order_by': self.order_by,
            'options_func_names': self._get_function_names(silk_request),
            'options_names': self._get_names(silk_request),
            'filters': filters
        }
        context.update(csrf(request))
        if silk_request:
            context['silk_request'] = silk_request
        if func_name:
            context['func_name'] = func_name
        if name:
            context['name'] = name
        objs = self._get_objects(show=show,
                                 order_by=order_by,
                                 func_name=func_name,
                                 silk_request=silk_request,
                                 name=name,
                                 filters=[BaseFilter.from_dict(x) for _, x in filters.items()])
        context['results'] = objs
        return context

    @method_decorator(login_possibly_required)
    @method_decorator(permissions_possibly_required)
    def get(self, request, *args, **kwargs):
        return render(request, 'silk/profiling.html', self._create_context(request, *args, **kwargs))

    @method_decorator(login_possibly_required)
    @method_decorator(permissions_possibly_required)
    def post(self, request):
        filters = filters_from_request(request)
        filters_as_dict = {ident: f.as_dict() for ident, f in filters.items()}
        self.filters_manager.save(request, filters_as_dict)
        return render(request, 'silk/profiling.html', self._create_context(request))

silk/views/raw.py
import logging

from django.http import HttpResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import View

from silk.auth import login_possibly_required, permissions_possibly_required
from silk.models import Request

Logger = logging.getLogger("silk.views.raw")


class Raw(View):

    @method_decorator(login_possibly_required)
    @method_decorator(permissions_possibly_required)
    def get(self, request, request_id):
        typ = request.GET.get("typ", None)
        subtyp = request.GET.get("subtyp", None)
        body = None
        if typ and subtyp:
            silk_request = Request.objects.get(pk=request_id)
            if typ == "request":
                body = silk_request.raw_body if subtyp == "raw" else silk_request.body
            elif typ == "response":
                Logger.debug(silk_request.response.raw_body_decoded)
                body = (
                    silk_request.response.raw_body_decoded
                    if subtyp == "raw"
                    else silk_request.response.body
                )
            return render(request, "silk/raw.html", {"body": body})
        else:
            return HttpResponse(content="Bad Request", status=400)

silk/views/sql.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import View

from silk.auth import login_possibly_required, permissions_possibly_required
from silk.models import Profile, Request, SQLQuery
from silk.utils.pagination import _page

__author__ = 'mtford'


class SQLView(View):
    page_sizes = [5, 10, 25, 100, 200, 500, 1000]
    default_page_size = 200

    @method_decorator(login_possibly_required)
    @method_decorator(permissions_possibly_required)
    def get(self, request, *_, **kwargs):
        request_id = kwargs.get('request_id')
        profile_id = kwargs.get('profile_id')
        try:
            per_page = int(request.GET.get('per_page', self.default_page_size))
        except (TypeError, ValueError):
            per_page = self.default_page_size
        context = {
            'request': request,
            'options_page_size': self.page_sizes,
            'per_page': per_page,
        }
        if request_id:
            silk_request = Request.objects.get(id=request_id)
            query_set = SQLQuery.objects.filter(request=silk_request).order_by('-start_time')
            for q in query_set:
                q.start_time_relative = q.start_time - silk_request.start_time
            page = _page(request, query_set, per_page)
            context['silk_request'] = silk_request
        if profile_id:
            p = Profile.objects.get(id=profile_id)
            page = _page(request, p.queries.order_by('-start_time').all(), per_page)
            context['profile'] = p
        if not (request_id or profile_id):
            raise KeyError('no profile_id or request_id')
        # noinspection PyUnboundLocalVariable
        context['items'] = page
        return render(request, 'silk/sql.html', context)

silk/templates/silk/cprofile.html
{% extends "silk/base/detail_base.html" %}
{% load silk_filters %}
{% load silk_nav %}
{% load silk_inclusion %}
{% load static %}

{% block pagetitle %}Silky - CProfile - {{ silk_request.path }}{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'silk/lib/viz-lite.js' %}"></script>
    <script type="text/javascript" src="{% static 'silk/lib/svg-pan-zoom.min.js' %}"></script>
    {{ block.super }}
{% endblock %}

{% block style %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'silk/css/components/summary.css' %}">
    <link rel="stylesheet" href="{% static 'silk/css/pages/cprofile.css' %}">
{% endblock %}

{% block menu %}
    {% request_menu request silk_request %}
{% endblock %}


{% block data %}
    <div class="wrapper">
        <div id="query-div">
            {% if silk_request.pyprofile %}
            <div id="pyprofile-div">
                <div class="heading">
                    <div class="inner-heading">CProfile</div>
                </div>
                <div class="description">
                    The below is a dump from the cPython profiler.
                </div>
                {% if silk_request.prof_file %}
                Click <a href="{% url 'silk:request_profile_download' request_id=silk_request.pk %}">here</a> to download profile.
                {% endif %}
                <pre class="pyprofile">{{ silk_request.pyprofile }}</pre>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

silk/templates/silk/profile_detail.html
{% extends "silk/base/detail_base.html" %}
{% load silk_filters %}
{% load silk_nav %}
{% load silk_inclusion %}
{% load static %}

{% block pagetitle %}Silky - Profile Detail - {{ silk_request.path }}{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'silk/lib/viz-lite.js' %}"></script>
    <script type="text/javascript" src="{% static 'silk/lib/svg-pan-zoom.min.js' %}"></script>
    {{ block.super }}
{% endblock %}

{% block style %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'silk/css/components/summary.css' %}">
    <link rel="stylesheet" href="{% static 'silk/css/pages/profile_detail.css' %}">
{% endblock %}

{% block menu %}
    {% profile_menu request profile silk_request %}
{% endblock %}

{% block data %}
    <div class="wrapper">
        <div id="query-div">
            <div id="query-info-div">
                {% profile_summary profile %}
            </div>
            <div class="heading">
                <div class="inner-heading">
                    {% if profile.file_path and profile.line_num %}
                        {{ profile.file_path }}:{{ profile.line_num }}{% if profile.end_line_num %}:{{ profile.end_line_num }}{% endif %}
                    {% else %}
                        Location
                    {% endif %}
                </div>
            </div>
            <div class="description">
                Below shows where in your code this profile was defined. If your profile was defined dynamically (i.e in your settings.py),
                then this will show the range of lines that are covered by the profiling.
            </div>
            {% if code %}
                <pre id="code"><code>{% code code actual_line %}</code></pre>
            {% elif code_error %}
                <div id="error-div">
                    {{ code_error }}
                </div>
            {% endif %}

            {% if silk_request.prof_file %}
            <div class="heading">
                <div class="inner-heading">Profile graph</div>
            </div>
            <div class="description">
                Below is a graph of the profile, with the nodes coloured by the time taken (red is more time). This should give a good indication of the slowest path through the profiled code.</div>

                <span>Prune nodes taking up less than </span>
                <input id='percent' type="text" value='5'
                       onkeypress='return event.charCode >= 48 && event.charCode <= 57 && $("#percent").val().length < 2'
                       oninput="createViz()"
                >

                </input>
                <span>% of the total time</span>

            </div>
            <div id="graph-div">
            </div>
            {% url 'silk:request_profile_dot' request_id=silk_request.pk as profile_dot_url %}
            {{ profile_dot_url|json_script:'profileDotURL' }}
            <script src="{% static 'silk/js/pages/profile_detail.js' %}"></script>
            {% endif %}

            {% if silk_request.pyprofile %}
            <div id="pyprofile-div">
                <div class="heading">
                    <div class="inner-heading">Python Profiler</div>
                </div>
                <div class="description">
                    The below is a dump from the cPython profiler.
                </div>
                {% if silk_request.prof_file %}
                Click <a href="{% url 'silk:request_profile_download' request_id=silk_request.pk %}">here</a> to download profile.
                {% endif %}
                <pre class="pyprofile">{{ silk_request.pyprofile }}</pre>
                {% endif %}
            </div>

        </div>
    </div>

{% endblock %}

silk/templates/silk/request.html
{% extends "silk/base/base.html" %}
{% load silk_filters %}
{% load silk_inclusion %}
{% load static %}
{% block pagetitle %}Silky - Request - {{ silk_request.path }}{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'silk/css/components/cell.css' %}"/>
    <link rel="stylesheet" href="{% static 'silk/css/components/numeric.css' %}"/>
    <link rel="stylesheet" href="{% static 'silk/css/components/button.css' %}">
    <link rel="stylesheet" href="{% static 'silk/css/components/heading.css' %}"/>
    <link rel="stylesheet" href="{% static 'silk/css/pages/request.css' %}"/>
    <link rel="stylesheet" href="{% static 'silk/lib/highlight/foundation.css' %}"/>
{% endblock %}
{% block js %}
    <script src="{% static 'silk/lib/highlight/highlight.pack.js' %}"></script>
    <script src="{% static 'silk/js/pages/request.js' %}"></script>
    <script src="{% static 'silk/js/components/cell.js' %}"></script>
{% endblock %}
{% block onload %}
{% endblock %}

{% block menu %}
    {% request_menu request silk_request %}
{% endblock %}

{% block data %}
    <div class="wrapper">
        <div id="request-summary">
            {% request_summary silk_request %}
        </div>
        <div id="request-info">
            {% if query_params %}
                {% heading 'Query Parameters' %}
                <pre><code>{{ query_params }}</code></pre>
            {% endif %}
            {% heading 'Request Headers' %}
            <table class="headers">
                {% for k,v in silk_request.headers.items %}
                    <tr>
                        <td class="key">{{ k.upper }}</td>
                        <td class="value">{{ v }}</td>
                    </tr>
                {% endfor %}
            </table>
            {% if silk_request.raw_body %}
                {% heading 'Raw Request Body' %}
                {% if silk_request.raw_body|length > 1000 %}
                    The raw request body is <b>{{ silk_request.raw_body|length }}</b> characters long
                    and hence is <b>too big</b> to show here.
                    Click <a href="{% url "silk:raw" silk_request.pk %}?typ=request&subtyp=raw">here</a> to view the raw request body.
                {% else %}
                    <pre>{{ silk_request.raw_body }}</pre>
                {% endif %}
            {% endif %}
            {% if silk_request.body %}
                {% heading 'Request Body' %}
                {% if silk_request.body|length > 1000 %}
                    The processed request body is <b>{{ silk_request.body|length }}</b> characters long
                    and hence is <b>too big</b> to show here.
                    Click <a href="{% url "silk:raw" silk_request.pk %}?typ=request&subtyp=processed">here</a> to view the request body.
                {% else %}
                    <div class="description">
                        This is the body of the HTTP request represented as JSON for easier reading.
                    </div>
                    <pre><code>{{ silk_request.body }}</code></pre>
                {% endif %}
            {% endif %}
            {% if silk_request.response.headers %}
                {% heading 'Response Headers' %}
                <table class="headers">
                    {% for k, v in silk_request.response.headers.items %}
                        <tr>
                            <td class="key">{{ k.upper }}</td>
                            <td class="value">{{ v }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% endif %}
            {% if silk_request.response.raw_body %}
                {% heading 'Raw Response Body' %}
                {% with raw_body=silk_request.response.raw_body_decoded %}
                    {% if raw_body|length > 1000 %}
                        The raw response body is <b>{{ raw_body|length }}</b> characters long
                        and hence is <b>too big</b> to show here.
                        Click <a href="{% url "silk:raw" silk_request.pk %}?typ=response&subtyp=raw">here</a> to view the raw response body.
                    {% else %}
                        <pre>{{ raw_body }}</pre>
                    {% endif %}
                {% endwith %}
            {% endif %}
            {% if silk_request.response.body %}
                {% heading 'Response Body' %}
                <div class="description">
                    This is the body of the HTTP response represented as JSON for easier reading.
                </div>
                {% if silk_request.response.body|length > 1000 %}
                    The response body is <b>{{ silk_request.response.body|length }}</b> characters long
                    and hence is <b>too big</b> to show here.
                    Click <a href="{% url "silk:raw" silk_request.pk %}?typ=response&subtyp=processed">here</a> to view the response body.
                {% else %}
                    <pre><code>{{ silk_request.response.body }}</code></pre>
                {% endif %}
            {% endif %}
            {% if curl %}
                {% heading 'Curl' %}
                <div class="description">
                    Curl is a command-line utility for transferring data from servers. Paste the following into
                    a terminal to repeat this request via command line.
                </div>
                <pre id="pre-curl"><code>{{ curl.strip }}</code></pre>
            {% endif %}
            {% if client %}
                {% heading 'Django Test Client' %}
                <div class="description">
                    The following is working python code that makes use of the Django test client. It can be used to
                    replicate this request from within a Django unit test, or simply as standalone Python.
                </div>
                <pre id="pre-curl"><code>{{ client.strip }}</code></pre>
            {% endif %}
        </div>
    </div>
{% endblock %}

silk/templates/silk/sql_detail.html
{% extends "silk/base/detail_base.html" %}
{% load static %}
{% load silk_filters %}
{% load silk_nav %}
{% load silk_inclusion %}

{% block pagetitle %}Silky - SQL Detail - {{ silk_request.path }}{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'silk/js/pages/sql_detail.js' %}"></script>
{% endblock %}

{% block style %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'silk/css/pages/sql_detail.css' %}"/>
{% endblock %}

{% block menu %}

    <a href="
        {% if silk_request and profile %}
            {% url "silk:request_and_profile_sql" silk_request.id profile.id %}
        {% elif silk_request %}
            {% url "silk:request_sql" silk_request.pk %}
        {% elif profile %}
            {% url "silk:profile_sql" profile.pk %}
        {% endif %}
    ">
        <div class="menu-item selectable-menu-item">
            <div class="menu-item-outer">
                <div class="menu-item-inner">&larr;</div>
            </div>
        </div>
    </a>

    <div class="menu-item menu-item-selected">
        <div class="menu-item-outer ">
            <div class="menu-item-inner">SQL Query</div>
        </div>
    </div>
{% endblock %}

{% block data %}
    <div class="wrapper">
        <div id="query-div">
            <pre id="query"><code>{{ sql_query.formatted_query|spacify|linebreaksbr }}</code></pre>
            <div id="query-info-div">
                <div id="time-taken-div">
                    <span class="numeric">{{ sql_query.time_taken }}<span class="unit">ms</span></span>
                </div>
                <div id="num-joins-div">
                    <span class="numeric">{{ sql_query.num_joins }}</span> joins
                </div>
            </div>

        </div>
        {% if analysis %}
        <div id="query-plan-div">
            <div class="heading">
                <div class="inner-heading">
                    Query Plan
                </div>
            </div>
            <code id="plan">{{ analysis | spacify | linebreaksbr }}</code>
        </div>
        {% endif %}
        <div id="traceback">
            <div class="heading">
                <div class="inner-heading">
                    Traceback
                </div>
            </div>
            <div class="description">
                The below is the Python stacktrace that leads up the execution of the above SQL query.
                Use it to figure out where and why this SQL query is being executed and whether or not
                it's actually neccessary.
            </div>
            {% for ln in traceback %}
                {% if ln %}
                    <div class="file-path {% if virtualenv_path not in ln %}not-{% else %}is-{% endif %}third-party">
                        {{ ln }}
                    </div>
                    {% if forloop.counter == pos %}
                        {% code code actual_line %}
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
    </div>


{% endblock %}